export const CONFIG = {
  PLATFORM_FEE_PERCENT: Number(process.env.NEXT_PUBLIC_PLATFORM_FEE_PERCENT || 5),
  PRO_MONTHLY_PRICE: Number(process.env.NEXT_PUBLIC_PRO_MONTHLY_PRICE || 10),
  ELITE_MONTHLY_PRICE: Number(process.env.NEXT_PUBLIC_ELITE_MONTHLY_PRICE || 25),
  FEATURED_GIG_PRICE: Number(process.env.NEXT_PUBLIC_FEATURED_GIG_PRICE || 1),
  TREASURY_WALLET_ADDRESS: process.env.NEXT_PUBLIC_PLATFORM_TREASURY || "0x9815A1a65B330F6CBEcD05d31C98a1C98C32b9A4", // Default dummy treasury for local verification
};
