export const CONFIG = {
  PLATFORM_FEE_PERCENT: Number(process.env.NEXT_PUBLIC_PLATFORM_FEE_PERCENT || 5),
  PRO_MONTHLY_PRICE: Number(process.env.NEXT_PUBLIC_PRO_MONTHLY_PRICE || 10),
  ELITE_MONTHLY_PRICE: Number(process.env.NEXT_PUBLIC_ELITE_MONTHLY_PRICE || 25),
  FEATURED_GIG_PRICE: Number(process.env.NEXT_PUBLIC_FEATURED_GIG_PRICE || 1),
  TREASURY_WALLET_ADDRESS: process.env.NEXT_PUBLIC_PLATFORM_TREASURY || process.env.TREASURY_ADDRESS || "0x079D9c349741C27565ee04e31E4174F640F512aE",
};
